package presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.HabitacionService;

/**
 *
 * @author pablo
 */
public class FrmVistaHabitacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmVistaHabitacion
     */
    public FrmVistaHabitacion() {
        initComponents();
        llenarTabla();
        this.setLocationRelativeTo(null);
    }
    
    private void ocultarColumnaIdHabitacion() {
        tablaListar.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaListar.getColumnModel().getColumn(0).setMinWidth(0);
        tablaListar.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void llenarTabla() {
        try {
            DefaultTableModel tableModel;
            HabitacionService service = new HabitacionService();
            tableModel = service.habitacionesDisponibles();
            tablaListar.setModel(tableModel);
            ocultarColumnaIdHabitacion();
            lblTotalRegistros.setText("Habitaciones disponibles: " + Integer.toString(service.getTotalRegistro()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblTotalRegistros = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaListar = new javax.swing.JTable();

        jPanel5.setBackground(new java.awt.Color(208, 219, 229));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Habitaciones disponibles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        lblTotalRegistros.setText("Registros");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addComponent(lblTotalRegistros)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(lblTotalRegistros)
                .addContainerGap())
        );

        tablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaListarMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListarMouseClicked
        
    }//GEN-LAST:event_tablaListarMouseClicked

    private void tablaListarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListarMousePressed
        if (evt.getClickCount() == 2) {
            int fila = tablaListar.getSelectedRow();
            String idHabitacion = tablaListar.getValueAt(fila, 0).toString();
            String numHabitacion = tablaListar.getValueAt(fila, 1).toString();
            FrmReserva.txtIdHabitacion.setText(idHabitacion);
            FrmReserva.txtNumeroHabitacion.setText(numHabitacion);
            this.dispose();
        }
    }//GEN-LAST:event_tablaListarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalRegistros;
    private javax.swing.JTable tablaListar;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscar1;
    private javax.swing.JTextField txtBuscar2;
    // End of variables declaration//GEN-END:variables
}
