package presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.ClienteService;

/**
 *
 * @author pablo
 */
public class FrmVistaCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmVistaCliente
     */
    public FrmVistaCliente() {
        initComponents();
        llenarTabla("");
        this.setLocationRelativeTo(null);
    }
    
    private void ocultarColumnaIdCliente() {
        tablaListar.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaListar.getColumnModel().getColumn(0).setMinWidth(0);
        tablaListar.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaListar.getColumnModel().getColumn(8).setMaxWidth(0);
        tablaListar.getColumnModel().getColumn(8).setMinWidth(0);
        tablaListar.getColumnModel().getColumn(8).setPreferredWidth(0);
    }
    
    private void llenarTabla(String documento) {
        try {
            DefaultTableModel tableModel;
            ClienteService service = new ClienteService();
            tableModel = service.mostrarTabla(documento);
            tablaListar.setModel(tableModel);
            ocultarColumnaIdCliente();
            lblTotalClientes.setText("Huéspedes registrados: " + Integer.toString(service.getTotalRegistro()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtBuscar2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tablaListar = new javax.swing.JTable();
        lblTotalClientes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentariosCliente = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(208, 219, 229));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de huespedes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N

        txtBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar2txtBuscarActionPerformed(evt);
            }
        });

        jLabel51.setText("Buscar por Documento:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarbtnBuscar4ActionPerformed(evt);
            }
        });

        tablaListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaListartablaListarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaListarMousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(tablaListar);

        lblTotalClientes.setText("Registros");

        txtComentariosCliente.setEditable(false);
        txtComentariosCliente.setColumns(20);
        txtComentariosCliente.setFont(new java.awt.Font("TlwgTypewriter", 1, 15)); // NOI18N
        txtComentariosCliente.setRows(5);
        txtComentariosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Comentarios del huesped", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 14))); // NOI18N
        jScrollPane2.setViewportView(txtComentariosCliente);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblTotalClientes)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaListartablaListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListartablaListarMouseClicked
        int fila = tablaListar.rowAtPoint(evt.getPoint());
        txtComentariosCliente.setText(tablaListar.getValueAt(fila, 8).toString());
        txtComentariosCliente.setLineWrap(true);
        txtComentariosCliente.setWrapStyleWord(true);
    }//GEN-LAST:event_tablaListartablaListarMouseClicked

    private void btnBuscarbtnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarbtnBuscar4ActionPerformed
        llenarTabla(txtBuscar2.getText());
    }//GEN-LAST:event_btnBuscarbtnBuscar4ActionPerformed

    private void txtBuscar2txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar2txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar2txtBuscarActionPerformed

    private void tablaListarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaListarMousePressed
        if (evt.getClickCount() == 2) {
            int fila = tablaListar.getSelectedRow();
            String idCliente = tablaListar.getValueAt(fila, 0).toString();
            String huesped = tablaListar.getValueAt(fila, 1).toString() + " " + tablaListar.getValueAt(fila, 2).toString();
            FrmReserva.txtIdCliente.setText(idCliente);
            FrmReserva.txtHuesped.setText(huesped);
            this.dispose();
        }
    }//GEN-LAST:event_tablaListarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVistaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblTotalClientes;
    private javax.swing.JTable tablaListar;
    private javax.swing.JTextField txtBuscar2;
    private javax.swing.JTextArea txtComentariosCliente;
    // End of variables declaration//GEN-END:variables
}
